name: family_tracker_parent
description: Aileİzi — Aile ve Çocuk Takip (Ebeveyn)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: 2.32.0
  firebase_auth: 4.16.0
  cloud_firestore: 4.17.5
  firebase_messaging: 14.7.10
  
  # Konum
  google_maps_flutter: ^2.5.3
  geolocator: 13.0.4
  
  # UI
  flutter_local_notifications: ^19.5.0
  cached_network_image: ^3.4.1
  intl: any
  google_fonts: ^6.2.1
  
  # State
  provider: ^6.1.1
  google_sign_in: 6.2.1
  http: ^1.2.2
  shared_preferences: ^2.5.3
  flutter_background_service: ^5.1.0
  firebase_storage: ^11.6.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
